{"name": "test_something", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "get_number = 356\n\n    def test_something(get_number):\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests\\something\\test_something.py:2: AssertionError"}, "start": 1721120182037, "stop": 1721120182037, "uuid": "9127e4e8-e83a-4e2d-b1f4-9c3bcd28cf3a", "historyId": "00cfec4e6a5f1c56560439b2d74d0afc", "testCaseId": "00cfec4e6a5f1c56560439b2d74d0afc", "fullName": "tests.something.test_something#test_something", "labels": [{"name": "parentSuite", "value": "tests.something"}, {"name": "suite", "value": "test_something"}, {"name": "host", "value": "DESKTOP-0U2FG1E"}, {"name": "thread", "value": "5592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.something.test_something"}]}