{"name": "test_something", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "get_number = 261\n\n    def test_something(get_number):\n        \"\"\"\n        Another test to check that 1 is equal to 1\n        \"\"\"\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests\\something\\test_something.py:5: AssertionError"}, "description": "\n    Another test to check that 1 is equal to 1\n    ", "start": 1721122912351, "stop": 1721122912351, "uuid": "03a8ae4b-0b32-4ae8-9ef1-4d820b5e343b", "historyId": "00cfec4e6a5f1c56560439b2d74d0afc", "testCaseId": "00cfec4e6a5f1c56560439b2d74d0afc", "fullName": "tests.something.test_something#test_something", "labels": [{"name": "parentSuite", "value": "tests.something"}, {"name": "suite", "value": "test_something"}, {"name": "host", "value": "DESKTOP-0U2FG1E"}, {"name": "thread", "value": "6472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.something.test_something"}]}